### ISSUE TITLE
Commas in text strings act as delimiters and cause the generated CSV file to have content that gets shifted to the next column

### ISSUE THREAD

**Issue by DogandElk** [vigneshuvi/SwiftCSVExport#8] opened 2018-02-02 14:55 UTC
This problem was fixed in a previous version but has resurfaced in th current 2.0 version

<img width="624" alt="screen shot 2018-02-02 at 8 42 12 am" src="https://user-images.githubusercontent.com/33180619/35739234-97d10e96-07f6-11e8-869f-3a04ce6904d0.png">
<img width="624" alt="screen shot 2018-02-02 at 8 42 12 am" src="https://user-images.githubusercontent.com/33180619/35739248-a42c26da-07f6-11e8-9211-ac16c808f841.png">

**Comment by kedolg** [comment] 2018-02-03 14:18
The problem is caused by commas in the body of the message.  Every time a comma is encountered the next content in line gets populated to the next column.  Returns do not as indicated by the \n.

**Comment by kedolg** [comment] 2018-02-03 16:53
I receive these errors :

**Comment by vigneshuvi** [comment] 2018-02-05 06:29
will check now and let you know?

Have you tried with my example?. It is working fine for me! Can you please let know the old version, you used so for now.

**Comment by DogandElk** [comment] 2018-02-05 14:15
THANKS AS ALWAY !

**Comment by vigneshuvi** [comment] 2018-02-06 03:53
Do you have this issue? Shall i close this ticket?

**Closed as completed** 2018-02-07 09:36 UTC

**Comment by DogandElk** [comment] 2018-02-07 10:50
Have you fixed this problem ?
If so have you create a new version ?

**Comment by vigneshuvi** [comment] 2018-02-07 11:04
Hi @DogandElk ,

i was unable to reproduce this issue. Can you please provide some sample data?

**Comment by vigneshuvi** [comment] 2018-02-07 11:28
@DogandElk 

Give sample formatted string which you used in the app?
